# Generated by Django 4.0.5 on 2022-06-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('CuentaBanco', models.CharField(max_length=20, verbose_name='Cuenta de Banco')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='PacientesMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AliasMascota', models.CharField(max_length=50, verbose_name='Alias de la mascota')),
                ('Especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('Raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('ColorPelo', models.CharField(max_length=20, verbose_name='Color de pelo')),
                ('FechaNacimiento', models.DateField(verbose_name='dd,mm,aaaa')),
                ('Vacunaciones', models.CharField(max_length=50, verbose_name='Vacunas')),
                ('IDClientesFamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteri.clientesfamilia', verbose_name='ClientesFamilia')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepersona', models.CharField(max_length=50, verbose_name='Nombre Persona')),
                ('apellidopersona', models.CharField(max_length=100, verbose_name='Apellido Persona')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(verbose_name='dd,mm,aaaa')),
                ('Enfermedad', models.CharField(max_length=150, verbose_name='Enfermedad que tiene')),
                ('FechaProxima', models.DateField(verbose_name='dd,mm,aaaa')),
                ('IDPacientesMascotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteri.pacientesmascotas', verbose_name='PacientesMascotas')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionPersonasClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDClientesFamilia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteri.clientesfamilia', verbose_name='ClientesFamilia')),
                ('IDPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteri.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaConsulta', models.DateField(verbose_name='Fecha de consulta')),
                ('Peso', models.CharField(max_length=10, verbose_name='Peso de tu mascota')),
                ('IDPacientesMascotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veteri.pacientesmascotas', verbose_name='PacientesMascotas')),
            ],
        ),
    ]
